.PHONY: clean All

All:
	@echo "----------Building project:[ UOCworking - Debug ]----------"
	@cd "UOCworking" && "$(MAKE)" -f  "UOCworking.mk"
clean:
	@echo "----------Cleaning project:[ UOCworking - Debug ]----------"
	@cd "UOCworking" && "$(MAKE)" -f  "UOCworking.mk" clean
